### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by AustEcon** [conduit-db/conduit-db#1]
- [x] Get mempool txs from the node directly (p2p) not via conduit_raw
- [x] Batch mempool txs for bulk flushing to MySQL
- [x] Test conduit_raw on HDD -> For full archive of mainnet I think it makes a lot of sense but should segregate raw block data 
from LMDB and store raw blocks as flat files outside of LMDB. (Result: Performs very well)
- [x] Add back the post-IBD mode event to conduit_index if the unnecessary mempool lookups show any slowdown for IBD 
(may be unnecessary now with fully in-memory mempool lookup table)
- [x] Upgrade db tables from height -> block num (with a separate table for block hash lookups)
- [x] Tune rocksdb for write-heavy loads
- [x] Script for printing out blockchain metrics such as cumulative blockchain size and total tx count etc. for translating logging timestamp progress to meaningful metrics about what to expect under ever increasing loads.
- [x] ShortHashing - essential for cutting footprint of index on NVMe storage and in-memory caches / network IO.
- [x] Return full tx hashes and pushdata hashes in the API
- [x] Test coverage of internal aiohttp API (json)
- [x] TSC merkle proof endpoint
- [x] Run tests in Azure pipeline
- [x] Reorg handling
- [x] Db repair on startup needs to do index-only lookups for the deletes so that it scales.
- [x] Add reorg functional testing
- [x] Pylint checks passing
- [x] Mypy checks passing
- [x] Tx offset data - move to flat files

Top priority post-MVP launch
- [x] Add db integrity check for conduit_raw (the same as is already done and working well for conduit_index).
- [x] Swagger documentation page (use Redoc https://github.com/Redocly/redoc)
- [x] Nginx proxy to add https://

Not required for MVP launch:
- [x] Simplify p2p network client
- [x] Dynamically adjust size of main batch size as the moving average block size increases (otherwise python dictionary caches etc. will get overly large if storing metadata for numerous large blocks at a time)
- [x] Make all configuration via a single top-level .env file
